# Generated by Django 5.0.14 on 2025-11-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_authtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                ("cta_label", models.CharField(default="Tez buyurtma", max_length=80)),
                ("cta_url", models.URLField(blank=True)),
                ("badge", models.CharField(blank=True, max_length=50)),
                ("image", models.ImageField(blank=True, null=True, upload_to="hero")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
