# Generated by Django 5.0.14 on 2025-11-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_herobanner"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewaySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(default="default", max_length=50, unique=True),
                ),
                ("sms_email", models.EmailField(blank=True, max_length=254)),
                ("sms_password", models.CharField(blank=True, max_length=255)),
                ("sender_name", models.CharField(default="4546", max_length=50)),
                (
                    "use_real_gateway",
                    models.BooleanField(
                        default=False,
                        help_text="Off -> test rejim (kod 0000). On -> haqiqiy Eskiz gateway ishlaydi.",
                    ),
                ),
                ("test_code", models.CharField(default="0000", max_length=6)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
