# Generated by Django 5.0.14 on 2025-11-29 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gatewaysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('language_code', models.CharField(default='uz', max_length=10)),
                ('is_premium', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_profile', to='core.customer')),
            ],
            options={
                'ordering': ['-last_login_at'],
                'indexes': [models.Index(fields=['telegram_id'], name='core_telegr_telegra_20a65c_idx'), models.Index(fields=['phone'], name='core_telegr_phone_c45aa3_idx')],
            },
        ),
    ]
