# Generated by Django 5.0.14 on 2025-11-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='KAMOLON', help_text='Saytning asosiy nomi (masalan: KAMOLON)', max_length=100, verbose_name='Sayt nomi')),
                ('site_logo', models.ImageField(blank=True, help_text='Sayt logotipi rasmi', null=True, upload_to='site/', verbose_name='Sayt logotipi')),
                ('site_description', models.CharField(blank=True, help_text='Qisqa tavsif yoki slogan', max_length=255, verbose_name='Sayt tavsifi')),
                ('phone_number', models.CharField(blank=True, help_text="Bog'lanish uchun telefon raqami", max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, help_text="Bog'lanish uchun email", max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, help_text='Kompaniya manzili', max_length=255, verbose_name='Manzil')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
