# Generated by Django 5.0.14 on 2025-11-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(default='OSH', help_text='Sayt nomi yonidagi matn (masalan: OSH, TAOM, va h.k.)', max_length=50, verbose_name='Sayt slogani'),
        ),
    ]
